INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_1', 'Korea_Seoul_1', '광화문 투어', '광화문 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_2', 'Korea_Seoul_2', '북촌 한옥 마을', '북촌 한옥 마을');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_3', 'Korea_Seoul_3', '명동 맛집 투어', '명동 맛집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_4', 'Korea_Seoul_4', '강남 쇼핑의 성지', '강남 쇼핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_5', 'Korea_Seoul_5', '서울 야경 투어', '서울 야경 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_6', 'Korea_Seoul_6', '한강에서 치맥을!', '한강에서 치맥을!');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_7', 'Korea_Seoul_7', '한강에서 자전거타기', '한강에서 자전거타기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_8', 'Korea_Seoul_8', '경복궁 투어', '경복궁 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_9', 'Korea_Seoul_9', '대한민국 역사 박물관', '대한민국 역사 박물관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_10', 'Korea_Seoul_10', '서대문 형무소 역사관', '서대문 형무소 역사관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_11', 'Korea_Seoul_11', '전쟁 기념관', '전쟁 기념관');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_12', 'Korea_Seoul_12', '자갈치 시장', '자갈치 시장');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_13', 'Korea_Seoul_13', '재래시장 투어', '재래시장 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_14', 'Korea_Seoul_14', '해운대와 광안대교 탐방', '해운대와 광안대교 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_15', 'Korea_Seoul_15', '성산일출봉과 흑돼지', '성산일출봉과 흑돼지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_16', 'Korea_Seoul_16', '새별오름과 노을 감상', '새별오름과 노을 감상');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_17', 'Korea_Seoul_17', '한국의 캘리포니아! 서핑의 성지', '한국의 캘리포니아! 서핑의 성지');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_18', 'Korea_Seoul_18', '빵에 진심인 도시! 대구 빵집 투어', '빵에 진심인 도시! 대구 빵집 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_19', 'Korea_Seoul_19', '한라산 하이킹', '한라산 하이킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Korea_Seoul_20', 'Korea_Seoul_20', '대나무 숲과 대나무 밥', '대나무 숲과 대나무 밥');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_21', 'Korea_Seoul_21', '보성녹차 밭 체험하기', '보성녹차 밭 체험하기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_22', 'Korea_Seoul_22', '태종대 투어', '태종대 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_23', 'Korea_Seoul_23', '감귤농장 체험', '감귤농장 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Korea_Seoul_24', 'Korea_Seoul_24', '정동진 해돋이', '정동진 해돋이');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_1', 'Asia_Mongolia_1', '테를지 국립공원', '테를지 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_2', 'Asia_Mongolia_2', '홍고린엘스 모래언덕', '홍고린엘스 모래언덕');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_3', 'Asia_Mongolia_3', '욜링암 트래킹', '욜링암 트래킹');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_4', 'Asia_Mongolia_4', '홉스굴 호수', '홉스굴 호수');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Mongolia_5', 'Asia_Mongolia_5', '몽골의 수도 울란바토르', '몽골의 수도 울란바토르');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_1', 'Europe_UK_1', '영국의 수도 런던', '영국의 수도 런던');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_2', 'Europe_UK_2', '스코틀랜드의 에든버러', '스코틀랜드의 에든버러');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_3', 'Europe_UK_3', '옥스퍼드 탐방', '옥스퍼드 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Europe_UK_4', 'Europe_UK_4', '레이크 디스트릭트 국립공원', '레이크 디스트릭트 국립공원');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Europe_UK_5', 'Europe_UK_5', '축구의 본고장 맨체스터', '축구의 본고장 맨체스터');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_1', 'Asia_China_1', '중국의 수도 베이징', '중국의 수도 베이징');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_China_2', 'Asia_China_2', '상하이의 샤오롱바오 맛집투어', '상하이의 샤오롱바오 맛집투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_3', 'Asia_China_3', '만리장성 투어', '만리장성 투어');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_4', 'Asia_China_4', '진시황릉과 병마용 관람', '진시황릉과 병마용 관람');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_China_5', 'Asia_China_5', '상하이 디즈니랜드', '상하이 디즈니랜드');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_1', 'NorthAmerica_US_1', '그랜드캐니언 탐방', '그랜드캐니언 탐방');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_2', 'NorthAmerica_US_2', '미국의 수도 뉴욕시티', '미국의 수도 뉴욕시티');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'NorthAmerica_US_3', 'NorthAmerica_US_3', '피자 먹으러 시카고', '피자 먹으러 시카고');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_4', 'NorthAmerica_US_4', '뉴올리언스의 재즈거리', '뉴올리언스의 재즈거리');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'NorthAmerica_US_5', 'NorthAmerica_US_5', '서핑의 도시 캘리포니아', '서핑의 도시 캘리포니아');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_1', 'Asia_Japan_1', '일본의 수도 도쿄', '일본의 수도 도쿄');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_2', 'Asia_Japan_2', '유니버셜 스튜디오', '유니버셜 스튜디오');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('그룹투어', 'Asia_Japan_3', 'Asia_Japan_3', '사슴공원 체험', '사슴공원 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_4', 'Asia_Japan_4', '훗카이도 료칸과 전통여관 체험', '훗카이도 료칸과 전통여관 체험');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
INSERT INTO tripTeam.package_content (packageType, packageId, packageImg, packageTitle, packageContent) VALUES ('자유여행', 'Asia_Japan_5', 'Asia_Japan_5', '후쿠오카 쇼핑 즐기기', '후쿠오카 쇼핑 즐기기');
